apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
spec:
  ports:
  - name: 8000-tcp
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: ${{ values.app_name }}
  type: ClusterIP
